# This is a basic workflow to help you get started with Actions

name: CI Staging

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the staging branch
  push:
    branches:
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "migrate"
  migrate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # gives the job access to the secrets and protection settings scoped to the staging environment
    environment: staging

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Flyway
        env:
          FLYWAY_VERSION: "7.7.1"
        run: | 
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}.tar.gz -o flyway-commandline-${FLYWAY_VERSION}.tar.gz \
          && tar -xzf flyway-commandline-${FLYWAY_VERSION}.tar.gz --strip-components=1 \
          && rm flyway-commandline-${FLYWAY_VERSION}.tar.gz
      - run: PATH=/flyway:$PATH
      - run: |
          .flyway -url ="jdbc:postgresql://${{secrets.DB_HOST}}:5432/${{secrets.DB_NAME}}" /
          - user="${{secrets.DB_USER}}" /
          - password="${{secrets.DB_PASS}}" /
          - locations="filesystem:migrations" info /
          migrate
          
